Revert "raphael: shim the GetPreviewImageData symbol on libpiex"
* Already in the source:
cd "$(dirname "/home/aoleary/msmT/out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "/home/aoleary/msmT/out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "/home/aoleary/msmT/out/soong"     --out "/home/aoleary/msmT/out"     -o /home/aoleary/msmT/out/soong/build.ninja --globListDir build --globFile /home/aoleary/msmT/out/soong/globs-build.ninja -t -l /home/aoleary/msmT/out/.module_paths/Android.bp.list --available_env /home/aoleary/msmT/out/soong/soong.environment.available --used_env /home/aoleary/msmT/out/soong/soong.environment.used.build Android.bp
error: hardware/lineage/compat/Android.bp:291:1: module "libpiex_shim" already defined
       device/xiaomi/raphael/camera/Android.bp:23:1 <-- previous definition here
11:04:43 soong bootstrap failed with: exit status 1

This reverts commit daf12acb2aab5b07317feaed62b341544ef3df81.